"""Temporal knowledge graph node schema definitions (v2.0)."""

from __future__ import annotations

NODE_LABELS: tuple[str, ...] = (
    "User",
    "Assessment",
    "Session",
    "Observation",
    "Prediction",
    "Risk",
    "Emotion",
    "Symptom",
    "Behaviour",
    "Embedding",
    "Recommendation",
    "Intervention",
    "TemporalEvent",
    "Model",
    "Research",
    # Legacy / modality features (MP4 Part 1)
    "RiskScore",
    "AudioFeature",
    "VisualFeature",
    "TextFeature",
    "ImageFeature",
    "Dataset",
)

# Stable entities — MERGE by natural key
STABLE_NODE_LABELS: frozenset[str] = frozenset({
    "User",
    "Assessment",
    "Session",
    "Model",
    "Research",
    "Embedding",
})

# Append-only entities — CREATE new node every time (never overwrite)
APPEND_ONLY_LABELS: frozenset[str] = frozenset({
    "Observation",
    "Prediction",
    "Risk",
    "Emotion",
    "Symptom",
    "Behaviour",
    "Recommendation",
    "Intervention",
    "TemporalEvent",
    "RiskScore",
})

NODE_PROPERTY_SCHEMAS: dict[str, tuple[str, ...]] = {
    "User": (
        "user_id",
        "external_id",
        "preferred_language",
        "timezone",
        "country",
        "consent_status",
        "privacy_mode",
        "edge_enabled",
        "cloud_enabled",
        "notification_preferences",
        "graph_version",
        "reasoning_version",
    ),
    "Assessment": (
        "assessment_id",
        "assessment_type",
        "assessment_version",
        "completed_at",
        "assessment_source",
        "assessment_duration",
        "language",
    ),
    "Session": (
        "session_id",
        "timestamp",
        "duration",
        "device",
        "platform",
        "network_type",
        "processing_time",
        "quality_score",
        "language",
        "battery_level",
        "offline_mode",
        "edge_processing",
        "cloud_processing",
    ),
    "Observation": (
        "observation_id",
        "timestamp",
        "confidence",
        "source_modality",
        "quality",
        "processing_version",
    ),
    "Prediction": (
        "prediction_id",
        "risk_probability",
        "binary_prediction",
        "severity_score",
        "confidence",
        "uncertainty",
        "temperature_scaled_probability",
        "model_version",
    ),
    "Risk": (
        "risk_id",
        "risk_level",
        "risk_score",
        "trend",
        "change_rate",
        "baseline",
        "confidence",
    ),
    "Emotion": (
        "emotion_id",
        "emotion_name",
        "probability",
        "confidence",
        "timestamp",
    ),
    "Symptom": (
        "symptom_id",
        "symptom_name",
        "severity",
        "confidence",
        "source",
        "timestamp",
    ),
    "Behaviour": (
        "behaviour_id",
        "behaviour_name",
        "value",
        "confidence",
        "duration",
        "timestamp",
    ),
    "Embedding": (
        "embedding_id",
        "embedding_type",
        "dimension",
        "model_name",
        "model_version",
        "storage_uri",
        "checksum",
    ),
    "Recommendation": (
        "recommendation_id",
        "recommendation_type",
        "priority",
        "generated_at",
        "confidence",
        "status",
    ),
    "Intervention": (
        "intervention_id",
        "type",
        "status",
        "start_time",
        "end_time",
        "completion_status",
    ),
    "TemporalEvent": (
        "event_id",
        "event_type",
        "timestamp",
        "relative_time",
        "absolute_time",
        "duration",
    ),
    "Model": (
        "model_id",
        "architecture",
        "version",
        "training_dataset",
        "training_date",
        "checkpoint_hash",
    ),
    "Research": (
        "experiment_id",
        "paper_version",
        "dataset_version",
        "feature_version",
        "git_commit",
        "pipeline_version",
    ),
}

NATURAL_KEYS: dict[str, str] = {
    "User": "user_id",
    "Assessment": "assessment_id",
    "Session": "session_id",
    "Observation": "observation_id",
    "Prediction": "prediction_id",
    "Risk": "risk_id",
    "Emotion": "emotion_id",
    "Symptom": "symptom_id",
    "Behaviour": "behaviour_id",
    "Embedding": "embedding_id",
    "Recommendation": "recommendation_id",
    "Intervention": "intervention_id",
    "TemporalEvent": "event_id",
    "Model": "model_id",
    "Research": "experiment_id",
    "RiskScore": "node_id",
}

SUPPORTED_EMOTIONS: tuple[str, ...] = (
    "Joy",
    "Sadness",
    "Neutral",
    "Fear",
    "Stress",
    "Loneliness",
    "Hopelessness",
    "Fatigue",
    "Calm",
    "Anxiety",
)

SUPPORTED_SYMPTOMS: tuple[str, ...] = (
    "Reduced Motivation",
    "Sleep Issues",
    "Low Energy",
    "Loss of Interest",
    "Social Withdrawal",
    "Negative Thinking",
    "Anxiety Indicators",
    "Stress Indicators",
)

SUPPORTED_BEHAVIOURS: tuple[str, ...] = (
    "Reduced Eye Contact",
    "Speech Pause",
    "Low Voice Energy",
    "Reduced Facial Activity",
    "Slow Speaking Rate",
    "Reduced Expression",
)

SUPPORTED_RECOMMENDATIONS: tuple[str, ...] = (
    "Breathing Exercise",
    "Meditation",
    "Sleep Hygiene",
    "Journal Writing",
    "Professional Counselling",
    "Emergency Helpline",
    "Mindfulness",
    "Physical Exercise",
)
